#!/bin/sh
# Probe: print [M1+6]..[M1+22], the P/1D runtime constant block's real
# contents, and write p1d_values.h.new from them -- candidate content for
# the table base.cc's findLit() mirror (see base.cc's #include
# "p1d_values.h") consults instead of a hand-derived one.
#
# One hand-written MADLEN deck, assembled and run directly under DUBNA --
# no ccom.bin/work.bin/pashelp, and no `base` either (a prior version
# compiled a tiny P2C driver with the host-native ./base, which meant
# p1d_values.h could not be regenerated before `base` existed at all).
# libc.bin (for PRINTO -- library 21) and the system-provided library 22
# (P/BX, P/EN, ...; see paslib/*.asm, which documents but does not build
# library 22) are the only things this needs.
#
# Notes:
#   - P/1D's real contents come from p_bx.asm's own static data image,
#     seeded at load time (see paslib/p_bx.asm) -- merely referencing
#     P/BX as an external pulls that module (and its data) in, so no
#     runtime call to P/BX/P/EN is needed, just `1,VTM,P/1D` to point M1
#     at it directly.
#   - The outer loop uses M2 (callee-saved) as its counter, not M14: M14
#     is scratch for computing each PRINTO argument's address, and PRINTO
#     is free to clobber non-callee-saved registers, so a loop counter
#     living in one of those would get corrupted after the first call.
#   - PRINTO(start, end, wordsPerLine, digitsPerWord) prints the words at
#     [start..end] in octal (matching PRINT8's own start/end-address
#     convention for a range) -- passing the same address for start and
#     end, as here, prints exactly one word.
#   - Stack handling verified against paslib/printo.dtran: the only
#     stack-mode push/pop inside PRINTO's own body is a 15,ATX,/15,ARX,
#     pair used back-to-back as self-balanced scratch for a cyclic-add
#     bit trick, not a pop of the caller's pushed argument addresses.
#     PRINTO never cleans up what it was called with, so the caller's
#     4 ,ITS,14 pushes are the caller's to pop -- which 15,UTM,-4 does.
#   - The module must be named PROGRAM (not e.g. PASCOMPL) for *execute
#     to recognize it as a runnable program rather than a library routine.
set -e

if [ ! -f libc.bin ]; then echo "$0: libc.bin is missing" >&2; exit 2; fi

cat << 'EOF' > tmp$$
*NAME probed
*disc:1/local
*file:libc,43
*libra:22
*libra:43
*call setftn:one,long
*assem
 PROGRAM :,NAME,
 P/1D    :,LC,40
 C/BX    :,SUBP,                    . pulls in initialization of P/1D
                1,VTM,P/1D
                2,VTM,6-22          . M2 := -16 (17 passes; M2 is callee-saved, survives PRINTO)
 LOOP:          2,UTC,
                1,XTA,22            . ACC := [M1+22+M2]
                ,ATX,VAL
                14,VTM,VAL
                ,ITS,14
                ,ITS,14
                14,VTM,N1           . number of words per line
                ,ITS,14
                14,VTM,N16          . number of digits in a word
                ,ITS,14
                ,NTR,2
                ,CALL,PRINTO
                15,UTM,-4           . pop the 4 pushed argument addresses
                2,VLM,LOOP
                ,CALL,STOP*
 N16:           ,INT,16
 N1:            ,INT,1
 VAL:           ,BSS,1
                ,END,
*execute
*end file
EOF
( ulimit -t 10; exec dubna tmp$$ ) > tmpraw$$
status=$?
cat tmpraw$$ | tee probe1d.lst
rm -f tmp$$ tmpraw$$
if [ $status -ne 0 ]; then
    echo "$0: probe run failed" >&2
    exit $status
fi

# Extract the first (of two identical) octal fields PRINTO prints per call,
# and write the 17 values to a temp file -- the caller (the Makefile's
# p1d_values.h rule) decides whether to swap it into place, only doing so
# if the content actually differs from what is there.
values=$(grep -E '^[0-7]{16}' probe1d.lst | awk '{print $1}')
count=$(echo "$values" | wc -l)
if [ "$count" -ne 17 ]; then
    echo "$0: expected 17 values, got $count" >&2
    exit 1
fi
{
    echo "// Generated by probe1d.sh from the real P/1D runtime constant"
    echo "// block ([M1+6]..[M1+22], see paslib/p_bx.asm) -- do not hand-edit."
    echo "static const int64_t P1D_VALUES[17] = {"
    offset=6
    echo "$values" | while read -r v; do
        printf '    /* [M1+%d] */ 0%s,\n' "$offset" "$v"
        offset=$((offset + 1))
    done
    echo "};"
} > p1d_values.h.new
rm -f probe1d.lst
echo "wrote p1d_values.h.new"
